Aplication/urls.py
from django.urls import path
from . import views
from .views import CreateBoss, DeleteBoss, EditBoss, BosList, MenuList, CreateMenu, EditMenu, DeleteMenu
from .views import CreateCategory, DeleteCategory, EditCategory, CategoryList
from .views import CreateRecipe, DeleteRecipe, EditRecipe, RecipeList
from .views import CreateRestaurant, DeleteRestaurant, EditRestaurant, RestaurantList
from .views import CreateEmployee, DeleteEmployee, EditEmployee, EmployeeList
from .views import CreateAdministrative, DeleteAdministrative, EditAdministrative, AdministrativeList
from .views import CreateManager, DeleteManager, EditManager, ManagerList
from .views import CreateChef, DeleteChef, EditChef, ChefList
from .views import CreateCashier, DeleteCashier, EditCashier, CashierList
from .views import CreateWaiter, DeleteWaiter, EditWaiter, WaiterList
from .views import CreateCustomer, DeleteCustomer, EditCustomer, CustomerList
from .views import CreatePay, DeletePay, EditPay, PayList
from .views import CreateOrder, DeleteOrder, EditOrder, OrderList
from .views import CreateDish, DeleteDish, EditDish, DishList
from .views import CreateIngredients, DeleteIngredients, EditIngredients, IngredientsList
from .views import CreateBill, DeleteBill, EditBill, BillList, LoggedHome
from django.urls import re_path

app_name = 'managment'

urlpatterns = [

    path('login/', views.login, name='login'),
    path('loggedhome/' , LoggedHome, name='loggedhome'),


    # Paths for boss
    path('create_boss/<int:restaurant_id>/', views.CreateBoss, name='create_boss'),
    path('boss_list/', BosList, name='boss_list'),
    path('edit_boss/<int:ID_M>/', EditBoss, name='edit_boss'),
    path('delete_boss/<int:ID_M>/', DeleteBoss, name='delete_boss'),
    
    #Paths for Menu
    path('create_menu/', CreateMenu, name='create_menu'),
    path('menu_list/', MenuList, name='menu_list'),
    path('edit_menu/<int:Menu_ID>/', EditMenu, name='edit_menu'),
    path('delete_menu/<int:Menu_ID>/', DeleteMenu, name='delete_menu'),
    
    #Paths for Category
    path('create_category/', CreateCategory, name='create_category'),
    path('category_list/', CategoryList, name='category_list'),
    path('edit_category/<int:Cat_ID>/', EditCategory, name='edit_category'),
    path('delete_category/<int:Cat_ID>/', DeleteCategory, name='delete_category'),
    
    #Paths for Recipe
    path('create_recipe/', CreateRecipe, name='create_recipe'),
    path('recipe_list/', RecipeList, name='recipe_list'),
    path('edit_recipe/<int:RecipeID>/', EditRecipe, name='edit_recipe'),
    path('delete_recipe/<int:RecipeID>/', DeleteRecipe, name='delete_recipe'),

    #Paths for Restaurant
    path('create_restaurant/', CreateRestaurant, name='create_restaurant'),
    path('restaurant_list/', RestaurantList, name='restaurant_list'),
    path('edit_restaurant/<int:ID>/', EditRestaurant, name='edit_restaurant'),
    path('delete_restaurant/<int:ID>/', DeleteRestaurant, name='delete_restaurant'),

    #Paths for Employee
    path('create_employee/', CreateEmployee, name='create_employee'),
    path('employee_list/', EmployeeList, name='employee_list'),
    path('managment/edit_employee/<int:EmployeeID>/', EditEmployee, name='edit_employee'),
    path('delete_employee/<int:EmployeeID>/', DeleteEmployee, name='delete_employee'),

    #Paths for Administratives
    path('create_administrative/', CreateAdministrative, name='create_administrative'),
    path('administrative_list/', AdministrativeList, name='administrative_list'),
    path('edit_administrative/<int:Admin_ID>/', EditAdministrative, name='edit_administrative'),
    path('delete_administrative/<int:Admin_ID>/', DeleteAdministrative, name='delete_administrative'),

    #Paths for Manager
    path('create_manager/', CreateManager, name='create_manager'),
    path('manager_list/', ManagerList, name='manager_list'),
    path('edit_manager/<int:Manager_ID>/', EditManager, name='edit_manager'),
    path('delete_manager/<int:Manager_ID>/', DeleteManager, name='delete_manager'),

    #Paths for Chef
    path('create_chef/', CreateChef, name='create_chef'),
    path('chef_list/', ChefList, name='chef_list'),
    path('edit_chef/<int:Chef_ID>/', EditChef, name='edit_chef'),
    path('delete_chef/<int:Chef_ID>/', DeleteChef, name='delete_chef'),

    #Paths for Cashier
    path('create_cashier/', CreateCashier, name='create_cashier'),
    path('cashier_list/', CashierList, name='cashier_list'),
    path('edit_cashier/<int:Cashier_ID>/', EditCashier, name='edit_cashier'),
    path('delete_cashier/<int:Cashier_ID>/', DeleteCashier, name='delete_cashier'),

    #Paths for Waiter
    path('create_waiter/', CreateWaiter, name='create_waiter'),
    path('waiter_list/', WaiterList, name='waiter_list'),
    path('edit_waiter/<int:Waiter_ID>/', EditWaiter, name='edit_waiter'),
    path('delete_waiter/<int:Waiter_ID>/', DeleteWaiter, name='delete_waiter'),

    #Paths for Customer
    path('create_customer/', CreateCustomer, name='create_customer'),
    path('customer_list/', CustomerList, name='customer_list'),
    path('edit_customer/<int:Cust_ID>/', EditCustomer, name='edit_customer'),
    path('delete_customer/<int:Cust_ID>/', DeleteCustomer, name='delete_customer'),

    #Paths for Pay
    path('create_pay/', CreatePay, name='create_pay'),
    path('pay_list/', PayList, name='pay_list'),
    path('edit_pay/<int:Payment_ID>/', EditPay, name='edit_pay'),
    path('delete_pay/<int:Payment_ID>/', DeletePay, name='delete_pay'),

    #Paths for Order
    path('create_order/', CreateOrder, name='create_order'),
    path('order_list/', OrderList, name='order_list'),
    path('edit_order/<int:OrderID>/', EditOrder, name='edit_order'),
    path('delete_order/<int:OrderID>/', DeleteOrder, name='delete_order'),

    #Paths for Dish
    path('create_dish/', CreateDish, name='create_dish'),
    path('dish_list/', DishList, name='dish_list'),
    path('edit_dish/<int:Dish_ID>/', EditDish, name='edit_dish'),
    path('delete_dish/<int:Dish_ID>/', DeleteDish, name='delete_dish'),

    #Paths for Ingredients
    path('create_ingredients/', CreateIngredients, name='create_ingredients'),
    path('ingredients_list/', IngredientsList, name='ingredients_list'),
    path('edit_ingredients/<int:Ingredient_ID>/', EditIngredients, name='edit_ingredients'),
    path('delete_ingredients/<int:Ingredient_ID>/', DeleteIngredients, name='delete_ingredients'),
    
    #Paths for Ingredients
    path('create_bill/', CreateBill, name='create_bill'),
    path('bill_list/', BillList, name='bill_list'),
    path('edit_bill/<int:Bill_ID>/', EditBill, name='edit_bill'),
    path('delete_bill/<int:Bill_ID>/', DeleteBill, name='delete_bill'),

    #re_path(r'^(?P<restaurant_id>\d+)/', include([
    #])),

]

Restaurant/urls.py
from django.contrib import admin
from Aplication import views
from django.urls import path, include
from Aplication.views import Home, BosList, MenuList, CategoryList, RecipeList, RestaurantList, EmployeeList, AdministrativeList, ManagerList, ChefList, CashierList, WaiterList, CustomerList, PayList, OrderList, DishList, IngredientsList, BillList, LoggedHome
from Aplication.views import CreateBoss, CreateMenu, CreateCategory, CreateRecipe, CreateRestaurant, CreateEmployee, CreateAdministrative, CreateManager, CreateChef, CreateCashier, CreateWaiter, CreateCustomer, CreatePay, CreateOrder, CreateDish, CreateIngredients, CreateBill

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('restaurant/<int:restaurant_id>/', include('Aplication.urls')),
    path('managment/', include('Aplication.urls', namespace='managment')),
    path('home/', Home, name='home_login'),
    path('loggedhome/',LoggedHome, name='loggedhome'),
    path('login/', views.login, name='login'),
    path('boss_list/', BosList, name='boss_list'),
    path('create_boss/<int:restaurant_id>/', CreateBoss, name='create_boss'),
    path('menu_list/',MenuList, name='menu_list'),
    path('create_menu/', CreateMenu, name='create_menu'),
    path('create_category/', CreateCategory, name='create_category'),
    path('category_list/',CategoryList, name='category_list'),
    path('recipe_list/', RecipeList, name='recipe_list'),
    path('create_recipe/', CreateRecipe, name='create_recipe'),
    path('restaurant_list/', RestaurantList, name='restaurant_list'),
    path('create_restaurant/', CreateRestaurant, name='CreateRestaurant'),
    path('create_employee/', CreateEmployee, name='create_employee'),
    path('employee_list/', EmployeeList, name='employee_list'),
    path('create_administrative/', CreateAdministrative, name='create_administrative'),
    path('administrative_list/', AdministrativeList, name='administrative_list'),
    path('create_manager/', CreateManager, name='create_manager'),
    path('manager_list/', ManagerList, name='manager_list'),
    path('create_chef/', CreateChef,name='create_chef'),
    path('chef_list/', ChefList, name='chef_list'),
    path('create_cashier/', CreateCashier,name='create_cashier'),
    path('cashier_list/', CashierList, name='cashier_list'),
    path('create_waiter/', CreateWaiter,name='create_waiter'),
    path('waiter_list/', WaiterList, name='waiter_list'),
    path('create_customer/', CreateCustomer, name='create_customer'),
    path('customer_list/', CustomerList, name='customer_list'),
    path('create_pay/', CreatePay, name='create_pay'),
    path('pay_list/', PayList, name='pay_list'),
    path('create_order/', CreateOrder, name='create_order'),
    path('order_list/', OrderList, name='order_list'),
    path('create_dish/', CreateDish, name='create_dish'),
    path('dish_list/', DishList, name='dish_list'),
    path('create_ingredients/', CreateIngredients, name='create_ingredients'),
    path('ingredients_list/', IngredientsList, name='ingredients_list'),
    path('create_bill/', CreateBill, name='create_bill'),
    path('bill_list/', BillList, name='bill_list'),
]
##urlpatterns = [
##    path('admin/', admin.site.urls),
##    path('home/', include('Aplication.urls', namespace='managment')),
##    path('restaurant/<int:restaurant_id>/', include('Aplication.restaurant_urls')),
##]

Aplication/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from .models import  Boss, Bill, Cashier, Category, Chef, Customer, Dish, Employees, Administrative, Ingredient, Manager, Menu, Order, Pay, Recipe, Restaurant, Waiter

class BossForm(forms.ModelForm):
    class Meta:
        model = Boss
        exclude = ['ID_M']
        fields = ['Salary', 'Name', 'Hire_Date', 'Email', 'Phone','Password']

class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['Menu_ID', 'Name', 'Description', 'Created_At']

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['Cat_ID', 'Type', 'Description', 'menu']

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['RecipeID', 'Type','Name','Description','PreparationTime']
        
class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['ID', 'Address', 'Name', 'Phone']

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = ['EmployeeID' ,'Name', 'Age', 'Sex', 'Phone', 'TimeEntry', 'Type', 'restaurant']
        labels = {
           'Restaurant'
        }

class AdministrativeForm(forms.ModelForm):
    class Meta:
        model = Administrative
        fields = ['Admin_ID', 'Salary', 'Employee_Phone', 'employee']


class ManagerForm(forms.ModelForm):
    class Meta:
        model = Manager
        fields = ['Manager_ID', 'Salary', 'Employee_Phone', 'employee']
        labels ={
            'employee':'Employee'
        }
        #Combobox for Employees
        def __init__(self, *arg, **kwargs):
            super(ManagerForm, self).__init__(*arg, **kwargs)
            self.fields['EmployeeID'].queryset = Employees.objects.all()



class ChefForm(forms.ModelForm):
    class Meta:
        model = Chef
        fields = ['Chef_ID', 'Salary', 'Employee_Phone', 'employee']

class CashierForm(forms.ModelForm):
    class Meta:
        model = Cashier
        fields = ['Cashier_ID', 'Salary', 'Employee_Phone', 'employee']

class WaiterForm(forms.ModelForm):
    class Meta:
        model = Waiter
        fields = ['Waiter_ID', 'Salary', 'Employee_Phone', 'employee']

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['Cust_ID', 'ContcNumber', 'Name', 'Age', 'Sex', 'Booking', 'Phone', 'waiter']

class PayForm(forms.ModelForm):
    class Meta:
        model = Pay
        fields = ['Method', 'Amount', 'Payment_ID', 'customer','Transaction_Date','order']

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['SaucersN', 'waiter', 'chef', 'customer_phone', 'customer', 'dishes']
        widgets = {'dishes': forms.CheckboxSelectMultiple}


class DishForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = ['Dish_ID', 'Name', 'Type', 'Cost', 'category', 'recipe']

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['Cost', 'Name', 'Amount', 'Unit', 'Expiration', 'recipe']

class BillForm(forms.ModelForm):
    class Meta:
        model = Bill
        fields = ['Bill_ID', 'cashier', 'customer','pay']

Aplication/templates/ManagerViews/ManagerList.html
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Lista de Managers</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="/static/admin/css/style2.css">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg" style="background-color: #D2B48C; border-bottom: 1px solid #ffffff;">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="margin-left: -14px;">
                  Restaurant
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/restaurant_list/">Restaurant List</a></li>
                    <li><a class="dropdown-item" href="/boss_list/">Boss List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Menu
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_menu/">Add Menu</a></li>
                    <li><a class="dropdown-item" href="/menu_list/">Menu List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Category
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="/create_category/">Add Categorys</a></li>
                  <li><a class="dropdown-item" href="/category_list/">Category List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Recipe
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_recipe/">Add Recipe</a></li>
                    <li><a class="dropdown-item" href="/recipe_list/">Recipe List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Employee
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_employee/">Add Employes</a></li>
                    <li><a class="dropdown-item" href="/employee_list/">Employees List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Administrative
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_administrative/">Add Administrative</a></li>
                    <li><a class="dropdown-item" href="/administrative_list/">Administrative List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Manager
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_manager/">Add Manager</a></li>
                    <li><a class="dropdown-item" href="/manager_list/">Manager List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Chef
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_chef/">Add Chef</a></li>
                    <li><a class="dropdown-item" href="/chef_list/">Chef List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Cashier
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_cashier/">Add Cashier</a></li>
                    <li><a class="dropdown-item" href="/cashier_list/">Cashier List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Waiter
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_waiter/">Add Waiter</a></li>
                    <li><a class="dropdown-item" href="/waiter_list/">Waiter List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Customer
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_customer/">Add Customer</a></li>
                    <li><a class="dropdown-item" href="/customer_list/">Customer List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Pay
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_pay/">Add Pay</a></li>
                    <li><a class="dropdown-item" href="/pay_list/">Pay List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Order
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_order/">Add Order</a></li>
                    <li><a class="dropdown-item" href="/order_list/">Order List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dish
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_dish/">Add Dish</a></li>
                    <li><a class="dropdown-item" href="/dish_list/">Dish List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Ingredient
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_ingredients/">Add Ingredient</a></li>
                    <li><a class="dropdown-item" href="/ingredients_list/">Ingredient List</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Bill
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/create_bill/">Add Bill</a></li>
                    <li><a class="dropdown-item" href="/bill_list/">Bill List</a></li>
                </ul>
              </li>
              <a class="navbar-brand" style="margin-right: 0px; margin-left: 6px;" href="/home/">Cerrar sesion</a>
            </ul>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>  
          </div>
        </div>
      </nav>
      <h1>Lista de Managers</h1>
      {% if managers %}
      <table>
          <thead>
              <tr>
                  <th>Manager_ID</th>
                  <th>Salary</th>
                  <th>Phone</th>
                  <th>Employee</th>
                  <th>Options</th>
              </tr>
          </thead>
          <tbody>
              {% for manager in managers %}
              <tr>
                  <td>{{ manager.Manager_ID }}</td>
                  <td>{{ manager.Salary }}</td>
                  <td>{{ manager.Employee_Phone }}</td>
                  <td>{{ manager.employee }}</td>
                  <td>
                      <a href="{% url 'managment:edit_manager' manager.Manager_ID %}">Edit</a>
                      <a href="{% url 'managment:delete_manager' manager.Manager_ID %}">Delete</a>
                  </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% else %}
      <h1>No records</h1>
      {% endif %}
    </div>
  </body>
</html>